### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by sobolevn** [Woile/commitizen#1]
Hello! I have found your tool and I think it looks awesome!

I really want to use it, but I have several questions about this project and its current state.

Here's some background:
1. I am using `commitizen.js`, `husky`, `commitlint` for my `node` and `vue` projects
2. I am using `pre-commit`, `gitlint` for my `python` projects

I want to use the same `json` configuration for both `python` and `js` projects. 
In `js` I use `cz-customizable` to specify any format I want. Do you have anything that works the same way?

How can I lint my conventional commits? In `js` there's a `commitlint` library, which works with conventional format: http://marionebl.github.io/commitlint/#/guides-local-setup

And the last question: what's the current project status? I am highly interested in making a reliable and cross-platform commit configuration and linting.

That's it.

Let me know if you need any help!

**Comment by Woile** [comment]
Any help is welcome! 

I found most of the JS tools overly complex, with a lot of dead links to the docs, and too tied to javascript.
I want this to be more of a general purpouse tool, and still be configurable using python (you can configure it in the `setup.cfg`). I want to run `cz c` and create a commit with the format I want.

If you want to create a commiter, in the readme you have [everything you need](https://github.com/Woile/commitizen#creating-a-commiter) to do it, they are similar to flask plugins, and you could upload them to pip separately to this project. Remember to set your commiter in the `.cz` in your home folder or your project folder.

For the linter I don't find it useful really, maybe you can explain a bit further its purpouse. But if this tools is generating the message and commiting, why do I need to lint?

Regarding the status, I'd really like to hear better ideas and how to improve the project. 

For my particular case, I'm only missing the changelog generator.

Glad you liked it,
Thank you!!
