### ISSUE TITLE
Add support for [skip ci]

### ISSUE THREAD

**Issue by marcosschroh** [Woile/commitizen#20]
Hi,

I was thinking and maybe could be a good feature to add the option `[skip ci]` to the commit message in order to skip the CI process. Most of CI tools like `CI Gitlab`, `Jenkins` explore the commit message and If it contains [ci skip] or [skip ci], using any capitalization, the commit will be created but the pipeline will be skipped.

Current situation: We want to `bump` a version after we detect some changes on the master branch. This process can be done by the CI process, so after the bumping, a new commit is generated and push to `master` branch.  This latest commit will trigger again the CI unless `[skip ci]` is found in the message. 

So, maybe the `bump` command could have an extra option like:

```
cz bump --skip-ci
```
generating: `version 0.6.0 → 0.7.0 [skip ci]` commit message. 

The `[skip ci]` message could be configured as well in order to support multiple CI conventions tools.  By default, should be ` [skip ci]`.

Make sense?

**Comment by Woile** [comment]
What do you think about custom commit message instead?
Similar to the way the tag template works. 

In the config you could set:

```
[tool.commitizen]
message = "bump: $old_version to $new_version [skip ci]"
```
My concern is that you might want to skip an specific CI [see here](https://github.com/travis-ci/travis-ci/issues/5032)

**Comment by marcosschroh** [comment]
Make sense as well and will work. 

> My concern is that you might want to skip a specific CI: 

Yes, this is why I was thinking that the "[skip ci] message" could be configured in order to support different CI like `[skip travis]`. 

Now the question is whether you as a developer want to have both options at the same time and probably the answer is no. 

So, closing the issue and may be reopened in the case that is needed.

**Comment by Woile** [comment]
Don't close it, I still have to add the feature. This is the reference

**Comment by marcosschroh** [comment]
I thought that the library already has support for custom commit messages, my bad. So, this feature is totally need it!
