### ISSUE TITLE
Handle git tag failure

### ISSUE THREAD

**Issue by Woile** [Woile/commitizen#32]
**Goal**
Handle error in case creating a tag fails

**Description**
Currently nothing is shown in case creating a tag fails.
We should at least print `c.err`.
https://github.com/Woile/commitizen/blob/master/commitizen/git.py#L7

**Comment by Lee-W** [comment]
Isn't it handled here?
https://github.com/Woile/commitizen/blob/master/commitizen/commands/bump.py#L127
Or do you think we should handle it in the tag function?

**Comment by Woile** [comment]
True, I think it can be closed. Thanks!
