### ISSUE TITLE
Non-invasive version bumping

### ISSUE THREAD

**Issue by WqyJh** [Woile/commitizen#35]
`cz bump` will read the old version, calculate the increment, and write the new version.

However, there's many way to define the project's version. For example, define an `__version__` variable in project's `__init__.py` or `__version__.py`, or in `pyproject.toml`. What's more, projects written in other languages may also need a tool to bump version. It's really hard to cover all of the scenes.

From my point of view, we need a tool to calculate project's SemVer purely based on the commit messages and to read the original version and set the new version could be done by other script, which make it be more extensible.

**Comment by Woile** [comment]
Hello @WqyJh , there are currently 2 ways to define the version, you can either use `pyproject.toml` (which is python specific), or you can use `.cz` which is intended for non pythonic projects. It's a configuration file like any other tool (black, isort, pre-commit, babel.config.js, etc), that's the only version that commitizen follows, it's like centralized there. 

If you specify your version in `__version__` or `__init__`, or anywhere else, you can use the [configuration of commitizen](https://woile.github.io/commitizen/config/) `files` in order for commitizen to automatically replace it with the next bump.

```
files = [
  "src/__init__.py"
   ] 
```

I agree with you, ideally everything should come from the git log message, but implementation wise is not that easy as you'd think, there are 2 main problems:

Let's say you retrieve the latest tag by date, how do you know that is the latest tag and not a patch from and older version?

Let's say you retrieve the "highest" tag, for git, the tag `4.7.0` > `4.61.0`, thus, you'd be calculating the increment for `4.7.0` which is wrong.

These cases forced the presence of a `version` inside commitizen configuration file.

**Comment by WqyJh** [comment]
Thank you for your reply!

According to the git flow, we bump version in `release` branch, which is checkout from `develop`
