### ISSUE TITLE
Retry functionality.

### ISSUE THREAD

**Issue by cbattista** [Woile/commitizen#40]
First off, thanks for this great tool.  My team wants to be using commitizen for our python package and we use a few of the other standard precommit hooks in our workflow, and these can fail.  Because we run commitizen _before_ these hooks are run, we wind up having to re-type our commit messages several times if the hooks fail out.  To avoid this problem, the `--retry` functionality that is present in the npm package would be very valuable here (See https://github.com/commitizen/cz-cli/issues/132 for related discussion.).  Thanks!

**Comment by Woile** [comment]
Interesting, I think it can be done, I'll come up with something this week.

**Comment by Woile** [comment]
`v1.6.0` has been released :tada: , please test it and let me know if it works properly!
