### ISSUE TITLE
handle commiting when no file change

### ISSUE THREAD

**Issue by Lee-W** [Woile/commitizen#45]
In [cz-cli](https://github.com/commitizen/cz-cli), if we run `git cz` without any file change, we'll get the message "No files added to staging! Did you forget to run git add?".

However, in `cz c`, we can still run the whole process.
The git commit is not actually created.

![Screen Shot 2019-11-08 at 5 53 05 PM](https://user-images.githubusercontent.com/5144808/68467190-ba08ce80-0250-11ea-9d0e-f617d9e25eed.png)

Maybe we can detect file change like cz-cli? Or, at least we could let the user know that this commit is not actually created.

**Comment by Woile** [comment]
I like the idea. I'm not sure whether we should do it before or after the
prompted questions. What would you suggest?

**Comment by Lee-W** [comment]
I would suggest do it before because in such situation all the actions after that are meaningless.

**Comment by Woile** [comment]
Agreed, I had that very same issues a few minutes ago haha. Feel free to create a PR to fix this.
