### ISSUE TITLE
Exception occurs when subject is not provided

### ISSUE THREAD

**Issue by Lee-W** [Woile/commitizen#46]
![Screen Shot 2019-11-08 at 5 51 42 PM](https://user-images.githubusercontent.com/5144808/68468058-3ea81c80-0252-11ea-9743-156925ce3f9f.png)

It happens due to this line.
https://github.com/Woile/commitizen/blob/master/commitizen/cz/conventional_commits/conventional_commits.py#L29

In [cz-cli](https://github.com/commitizen/cz-cli), they simple ignore it and generate an empty commiit.

![Screen Shot 2019-11-08 at 5 51 50 PM](https://user-images.githubusercontent.com/5144808/68468206-862ea880-0252-11ea-8063-90288693c848.png)

I like your idea more, but it seems to me that we can handle the exception in a better way.

**Comment by Woile** [comment]
Yeah, to me it doesn't make sense if no subject is provided. Wanna make a PR to catch the filter errors?

**Comment by Lee-W** [comment]
🙆‍♂

**Comment by Lee-W** [comment]
In the current implementation, the `NoSubjectException` is an exception only for `ConventionalCommitsCz`. Thus, it does not make sense to me catch this exception in `commands/commit.py`. Maybe we can add a `error.py` under `cz/` which contains all the possible excepction and a base exception like `CommitzenException` so that catching `CommitzenException` in `commands/commit.py` would make more sense. What do you think about this idea?

**Comment by Woile** [comment]
I like the idea, I would call the file `exceptions.py` though

**Comment by Woile** [comment]
Thanks for the help @Lee-W I'm closing this issue now
