### ISSUE TITLE
Support `prompt-toolkit>=2.0.0`.

### ISSUE THREAD

**Issue by sovknaf** [Woile/commitizen#5]
I'm running into some dependency problems. `pip install` ends with either:

```
mycli 1.18.1 has requirement prompt-toolkit<2.0.5,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.
jupyter-console 6.0.0 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.
ipython 7.0.1 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.
```

or 

```
commitizen 0.9.10 has requirement prompt-toolkit==1.0.15, but you'll have prompt-toolkit 2.0.4 which is incompatible.
```

depending on which order I install things. I had the same problem with dependencies on different versions of `prompt-toolkit` just a couple of weeks ago, between `mycli` and `ipython`, but thankfully, `mycli` updated its dependency recently.

It would be nice to see `commitizen` upgrade its dependency for `prompt-toolkit`, so we can have them installed in the same environment. Cheers!

**Comment by Woile** [comment]
No problem, I'll update it this week

**Comment by Woile** [comment]
Hey @sovknaf the underlying library used by commitizen (waaaaat), unfortunately, is using `prompt-toolkit==1.0.15`, and the api for `2.x` of `prompt-toolkit` has changed a lot, so, they have no plans of updating it. I'll try to remove the dependency but it'll be some heavy work, so I cannot promise to have results soon, sorry.

**Comment by Woile** [comment]
Version 1.0 uses `questionary` which also uses `prompt-toolkit>2`
