### ISSUE TITLE
New command: cz init

### ISSUE THREAD

**Issue by Woile** [Woile/commitizen#57]
#### Goal
Make it easier for users to use commitizen

#### Description
Let's suppose we have an already existing repo without commitizen.
The user types `cz init` and we try to be smart and detect some information:

1. Find last tag and ask if that is the latest tag. If not prompt which is the latest tag.
2. With that data we can fill the `version` in `[tool.commitizen]`.
3. Detect if the tag begins with `v` or not and define the `tag_format` in `[tool.commitizen]`
4. Find files with a reference to the latest version and define the `files` in `[tool.commitizen]`, we could let the user choose which files from the found should be added (with a multi-choice from questionary).
5. Ask to the user if they want the changelog to be generated from scratch if not present.

This is my initial draft, I'm not sure what else could be detected. Potentially we could ask for every configuration, but it's important to keep it short. It's not about customizing, but initializing quickly. If the user wants to customize more -> read the docs.

**Comment by Lee-W** [comment]
I'm working on it.
[init_command](https://github.com/Lee-W/commitizen/tree/init_command)

It seems to me adding "name" in init step is also a reasonable option.
Currently, I'm not sure how "files" should be implement. Do text search no the whole project to find version is defined in which files does not seem to be a good way.

**Comment by Woile** [comment]
Yes, the name should be added, and should use as options the available rules (even the plugins). It shouldn't be a problem

We could search in the current directory and inside a folder called `src` or like the project name (for this project would be `commitizen`), and make it not recursively.

```
.
src/
commitizen/
```

**Comment by Lee-W** [comment]
It seems to me we might refactor part of the config so that this enhancement can be finished. One of the problems I encounter now is that I'm not able to distinguish the default config and config load from files.
My Initial thought is to have a `BaseConfig` abstract class, `DefaultConfig`, `TomlConfig`. The difference in each child class will be how to parse config so that we might be able to support other common data formats. I think `json` would be a good choice. It's commonly used and not as hard to handle as `ini` does.

As for the `version_files`, do you mean code like `glob.glob('*version*')` and `glob.glob(*/*version*)` ?

**Comment by Woile** [comment]
Fine by me, let's give it a try, I think the config part needs some love.

Regarding the `version_files` I was thinking more like:
1. `ls src/` `ls .` `ls commitizen` (maybe using `os.walk` or `os.listdir`)
2. Get the *files* only (ignore directories).
3. Search for the `current_version` (selected in the first step). This doesn't need to be super fast, we can show a `Searching for version files...` with some sort of [animation](https://stackoverflow.com/questions/22029562/python-how-to-make-simple-animated-loading-while-process-is-running). It could be a function yielding the files found with a timeout of 5 secs.

**Comment by Lee-W** [comment]
Maybe we can discuss more on the "vesrion_files" part in the future, I'll first work on the refactoring and other functionaility of `init`.

**Comment by Woile** [comment]
Released on `1.12.0` :tada:

**Comment by rnc** [comment]
@Woile Isn't `init` missing from the top level readme? It also seems to be missing when running -h ?

**Comment by Woile** [comment]
Indeed it's missing in the README, but it works fine with `-h`. Check that you have the latest version `python3 -m pip install -U commitizen`

**Comment by rnc** [comment]
@Woile Apologies I hadn't refreshed the install to get the `-h` working. Doh!
