### ISSUE TITLE
Create github template for a commitizen plugin

### ISSUE THREAD

**Issue by Woile** [Woile/commitizen#58]
#### Goal
Let users create a cz package for their current project.

#### Description
Let's say users have some different commiting rules (not using conventional-commits). Right now the information in  [customization](https://woile.github.io/commitizen/customization/) guides the user in the creation of the plugin. We could have a github template that automates this (or a cookiecutter?).

The idea would be to assist in the creation of the folder structure and filling the boring parts.

```bash
.
├── cz_jira.py
└── setup.py
```

A link to this template should be added into our docs.

**Comment by Lee-W** [comment]
I've created a template for it. 
https://github.com/Lee-W/commitizen_cz_template
