### ISSUE TITLE
New command: cz check

### ISSUE THREAD

**Issue by Woile** [Woile/commitizen#59]
#### Goal
Prevent users from commiting if it doesn't match the current cz rules.

#### Description
Let's say a team is using as cz rule `conventional-commits`, and they want to enforce the project to always use conventional-commits by doing this in a `pre-commit` hook. 
Adding the command `cz check` would make it easy to validate this.

**Comment by dany2691** [comment]
I found this [post](https://prahladyeri.com/blog/2019/06/how-to-enforce-conventional-commit-messages-using-git-hooks.html) on the web, it's about how to create your own hook and I think it's not necessary use pre-commit. The author of the post points out that we have to create a file called commit-msg  inside '.git/hooks/', change the permissions of the file and each time a commit is created this file will be executed.

**Comment by Woile** [comment]
Hello @dany2691 thanks for the link. The idea of `pre-commit` is to not manage different scripts manually. If we create a `commit-msg` we may step on an already created script.

But using pre-commit or not is not the point. If a user manually creates the script `commit-msg`, they still need to run `cz check` inside it. So the idea is to create a check command which could be used in a `commit-msg`, is up to the user whether to use `pre-commit` or not.

**Comment by dany2691** [comment]
For example:

commit-msg

```bash
#!/bin/bash

MSG_FILE=$1
cz check --commit-msg-file $MSG_FILE
```
