### ISSUE TITLE
Investigation on how to run: git cz

### ISSUE THREAD

**Issue by Woile** [Woile/commitizen#60]
#### Goal
Be able to run `git cz` instead of `cz c`.

#### Description
I haven't researched much but I know it's possible to add some hook or plugin to git in order to add a new command. It's a nice to have. Maybe it could be part of `cz init`.

**Comment by alanjcastonguay** [comment]
This only requires an executable named `git-cz` on the user's `PATH`.

```
$ cat git-cz 
#!/usr/bin/env python
from __future__ import print_function

if __name__ == '__main__':
  print("hello world cz")
```

```shell
$ chmod +x git-cz
$ git cz
hello world cz
```

**Comment by Woile** [comment]
Awesome! Do you think it would be possible to add a command to generate this script?
I think your example can be added as documentation in the meanwhile.

Thanks!

**Comment by alanjcastonguay** [comment]
If the existing `commitizen.cli:main` is appropriate to run, this is a one-line change to `pyproject.toml`. Added PR.
